// components/feedback/FeedbackForm.tsx
'use client';

import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';

import { Button } from '@/app/components/ui/button';
import { Card } from '@/app/components/ui/card';
import {
  Form,
  FormField,
  FormItem,
  FormLabel,
  FormDescription,
  FormMessage
} from '@/app/components/ui/form';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from '@/app/components/ui/select';

import { toast } from 'sonner';
import { FeedbackService } from '@/app/utils/supabase/supabase';
import { EmailSendingAnimation, ErrorPopup, SuccessPopup } from '@/app/components/ui/animations/email';
import { FeedbackFormData, feedbackSchema } from '@/lib/validators';
import { FeedbackType } from '@/lib/types/folklore';

interface FeedbackFormProps {
  itemId: string;
  itemCategory: 'riddle' | 'idiom' | 'proverb';
  onSuccess?: () => void;
}

export const FeedbackForm: React.FC<FeedbackFormProps> = ({
  itemId,
  itemCategory,
  onSuccess
}) => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showSuccess, setShowSuccess] = useState(false);
  const [showError, setShowError] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');

  const form = useForm<FeedbackFormData>({
    resolver: zodResolver(feedbackSchema),
    defaultValues: {
      itemId: itemId,
      category: { category: itemCategory },
      feedBackType: { feedBackType: 'meaning' },
      message: '',
      userEmail: '',
    },
  });

  const onSubmit = async (data: FeedbackFormData) => {
    setIsSubmitting(true);
    setShowError(false);
    setErrorMessage('');

    try {
      await FeedbackService.createFeedback({
        id: '', // id will be generated by the database
        created_at: '', // created_at will be set by the database
        itemId: data.itemId,
        category: data.category,
        feedBackType: data.feedBackType,
        message: data.message,
        useremail: data.userEmail || undefined,
      });

      form.reset({
        itemId: itemId,
        category: { category: itemCategory },
        feedBackType: { feedBackType: 'meaning' },
        message: '',
        userEmail: '',
      });

      setShowSuccess(true);
      toast.success('Feedback submitted successfully!');

      if (onSuccess) onSuccess();

      setTimeout(() => {
        setShowSuccess(false);
      }, 3000);

    } catch (error) {
      console.error('Failed to submit feedback:', error);
      setErrorMessage(error instanceof Error ? error.message : 'Failed to submit feedback. Please try again.');
      setShowError(true);
      toast.error(errorMessage);
    } finally {
      setIsSubmitting(false);
    }
  };

  if (isSubmitting) {
    return (
      <Card className="p-8 max-w-2xl mx-auto bg-gradient-to-br from-card to-card/80 border-border/50">
        <div className="flex flex-col items-center justify-center min-h-[300px]">
          <EmailSendingAnimation
            onComplete={() => setIsSubmitting(false)}
          />
        </div>
      </Card>
    );
  }

  return (
    <Card className="p-8 max-w-2xl mx-auto bg-gradient-to-br from-card to-card/80 border-border/50 shadow-lg">
      <div className="space-y-6">
        <div>
          <h2 className="text-2xl font-bold text-foreground flex items-center gap-2">
            <span>📧</span> Send Feedback
          </h2>
          <p className="text-muted-foreground mt-1">
            Help us improve by sharing your feedback on this {itemCategory}.
          </p>
        </div>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            <FormField
              control={form.control}
              name="feedBackType"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Feedback Type</FormLabel>
                  <Select
                    onValueChange={(value) => field.onChange({ feedBackType: value as any })}
                    defaultValue={field.value.feedBackType}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select feedback type" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="translation">🔤 Translation Issue</SelectItem>
                      <SelectItem value="meaning">💡 Meaning Clarification</SelectItem>
                      <SelectItem value="options">❓ Options Problem</SelectItem>
                      <SelectItem value="context">📚 Context Issue</SelectItem>
                      <SelectItem value="lexical">📖 Lexical Issue</SelectItem>
                    </SelectContent>
                  </Select>
                  <FormDescription>
                    What type of feedback are you providing?
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="message"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Your Feedback</FormLabel>
                  <textarea
                    placeholder="Please provide detailed feedback..."
                    className="min-h-[120px] file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input w-full min-w-0 rounded-md border bg-transparent px-3 py-2 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive resize-y"
                    {...field}
                  />
                  <FormDescription>
                    Be specific about what can be improved. Minimum 10 characters.
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="userEmail"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Email (optional)</FormLabel>
                  <input
                    type="email"
                    placeholder="your@email.com"
                    className="file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input h-10 w-full min-w-0 rounded-md border bg-transparent px-3 py-2 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive"
                    {...field}
                  />
                  <FormDescription>
                    We'll contact you if we need clarification. Your email won't be shared.
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />

            <Button
              type="submit"
              className="w-full bg-gradient-to-r from-blue-600 to-indigo-700 hover:from-blue-700 hover:to-indigo-800 text-white font-medium py-6 text-lg"
              disabled={isSubmitting}
            >
              {isSubmitting ? (
                <span className="flex items-center justify-center">
                  <span className="animate-spin mr-2">📧</span>
                  Sending Feedback...
                </span>
              ) : (
                'Submit Feedback'
              )}
            </Button>
          </form>
        </Form>
      </div>

      {showSuccess && (
        <SuccessPopup
          message="Thank you! Your feedback has been received and will be reviewed by our team. You will receive a soon."
          onClose={() => setShowSuccess(false)}
        />
      )}

      {showError && (
        <ErrorPopup
          message={errorMessage}
          onClose={() => setShowError(false)}
        />
      )}
    </Card>
  );
};
