export const CONFIG = {
  PAPERLESS_API_BASE: 'http://172.30.235.111:8010',
  PAPERLESS_SEARCH_URL: process.env.PAPERLESS_SEARCH_URL,
  PAPERLESS_API_TOKEN: process.env.PAPERLESS_API_KEY,
  PAPERLESS_TAGS_URL: process.env.PAPERLESS_TAGS_URL,
  PAPERLESS_API_VERSION: process.env.PAPERLESS_API_VERSION || '9',
  PAPERLESS_ACCESS_KEY: process.env.PAPERLESS_ACCESS_KEY,
  DEFAULT_SEARCH_LIMIT: 5,
  MAX_SEARCH_STRATEGIES: 4,
  CACHE_TTL: 5 * 60 * 1000, // 5 minutes
  MAX_CONVERSATION_HISTORY: 10,
  CONTENT_PREVIEW_LENGTH: 300,
  TIMEOUTS: {
    PAPERLESS: 10000, // 10 seconds
  },
  LIMITS: {
    MAX_TAGS_PER_DOCUMENT: 10,
    SEARCH_RESULTS: 8,
  },
} as const;
